// <auto-generated />
namespace MyFirstMvcEfAppProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class purchaserequestlineitemscontroller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(purchaserequestlineitemscontroller));
        
        string IMigrationMetadata.Id
        {
            get { return "201706141937060_purchase-request-lineitems-controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
