// <auto-generated />
namespace MyFirstMvcEfAppProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatestoproduccontrol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatestoproduccontrol));
        
        string IMigrationMetadata.Id
        {
            get { return "201706151807214_updates-to-produccontrol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
