// <auto-generated />
namespace MyFirstMvcEfAppProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateduserdetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateduserdetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201706151400453_updated-user-details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
